"""Tests for the A/B judge script and bench server-log parsing.

Covers the review findings: ComfyUI prints "Prompt executed in HH:MM:SS" once a
run passes ~10 minutes (the decimal-seconds-only regex silently fell back to an
earlier run's line), log matches must be anchored to the current run, and the
judge script must exit 2 with judged:false for anything that is not a real
judgment (no env, extraction failure, VLM error).
"""
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


profile = _load("bench_profile_under_test", ROOT / "bench" / "profile.py")
ab_judge = _load("ab_judge_under_test", ROOT / "scripts" / "ab_judge.py")


# ---------------------------------------------------------------- log parsing
def test_prompt_exec_seconds_both_formats():
    sec = re.compile(
        r"Prompt executed in (?:([0-9.]+) seconds|(\d+):(\d{2}):(\d{2}))")
    assert profile.prompt_exec_seconds(sec.search("Prompt executed in 198.14 seconds")) == 198.14
    # ComfyUI switches to HH:MM:SS past ~10 min (the 768p side-A run: 625s)
    assert profile.prompt_exec_seconds(sec.search("Prompt executed in 00:10:25")) == 625.0


def test_last_log_match_never_reads_before_offset(tmp_path):
    """A run must only see its own log lines, never an earlier run's."""
    log = tmp_path / "server.log"
    log.write_text("line1: Prompt executed in 198.14 seconds\n")
    stale_size = log.stat().st_size
    log.write_text(log.read_text() + "line2: Prompt executed in 00:10:25\n")
    m = profile.last_log_match(str(log), profile.PROMPT_EXEC_RE, from_offset=stale_size)
    assert profile.prompt_exec_seconds(m) == 625.0
    # anchored past both lines: no match, no silent fallback to line1
    assert profile.last_log_match(str(log), profile.PROMPT_EXEC_RE,
                                  from_offset=log.stat().st_size) is None


# ------------------------------------------------------------------ ab_judge
def _tiny_video(path: Path) -> Path:
    """1s test video generated by code (no hand-crafted fixtures)."""
    r = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i",
         "testsrc=duration=1:size=320x240:rate=8", str(path)],
        capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    return path


def test_ab_judge_no_env_is_not_a_judgment(tmp_path, monkeypatch):
    monkeypatch.delenv("OPEN_VIDEO_VLM_URL", raising=False)
    monkeypatch.delenv("OPEN_VIDEO_VLM_MODEL", raising=False)
    v = _tiny_video(tmp_path / "v.mp4")
    out = tmp_path / "receipt.json"
    rc = ab_judge.main(["--a-video", str(v), "--b-video", str(v),
                        "--prompt", "p", "--out", str(out),
                        "--frames-root", str(tmp_path / "frames")])
    assert rc == 2
    assert json.loads(out.read_text())["summary"]["judged"] is False


def test_ab_judge_extraction_failure_is_not_a_judgment(tmp_path, monkeypatch):
    monkeypatch.setenv("OPEN_VIDEO_VLM_URL", "http://127.0.0.1:9/v1/chat/completions")
    monkeypatch.setenv("OPEN_VIDEO_VLM_MODEL", "test-vlm")
    fake = tmp_path / "corrupt.mp4"
    fake.write_bytes(b"not a video")
    out = tmp_path / "receipt.json"
    rc = ab_judge.main(["--a-video", str(fake), "--b-video", str(fake),
                        "--prompt", "p", "--out", str(out),
                        "--frames-root", str(tmp_path / "frames")])
    assert rc == 2
    d = json.loads(out.read_text())
    assert d["summary"]["judged"] is False
    assert d["a"]["verdict"] == "extraction_error"


def test_ab_judge_happy_path_separate_frame_dirs(tmp_path, monkeypatch):
    calls = []

    def fake_vision_fn(frames, prompt):
        calls.append(list(frames))
        return {"score": 0.9, "artifacts": "", "missing_elements": []}

    monkeypatch.setenv("OPEN_VIDEO_VLM_URL", "http://127.0.0.1:9/v1/chat/completions")
    monkeypatch.setenv("OPEN_VIDEO_VLM_MODEL", "test-vlm")
    monkeypatch.setattr(ab_judge, "vision_fn_from_env", lambda: fake_vision_fn)
    v = _tiny_video(tmp_path / "v.mp4")
    out = tmp_path / "receipt.json"
    rc = ab_judge.main(["--a-video", str(v), "--b-video", str(v),
                        "--prompt", "p", "--out", str(out),
                        "--frames-root", str(tmp_path / "frames")])
    assert rc == 0
    d = json.loads(out.read_text())
    assert d["summary"]["judged"] is True
    assert d["a"]["score"] == 0.9
    # the two sides' frame lists must not alias (separate directories)
    assert Path(d["a"]["frames"][0]).parent != Path(d["b"]["frames"][0]).parent
    assert d["judge"]["model"] == "test-vlm"
    assert len(calls) == 2
